### ISSUE TITLE
I can't put multiple of the same unstackable items in.

### ISSUE THREAD

**Issue by Boodlyneck** [JimiIT92/BundlesMod#3]
**Describe the bug**
It won't let me put 2 of the same unstackable items in.
(2 diamond helmets or 2 mending books for example) 

It will let me put 2 diamond helmets if one is damaged though.
I've tested this in 1.16.3 and 1.15.2 and they both had the same behavior.

Maybe this is the intended behavior?

Great mod though! I plan to put this in my next video.
You'll probably have this all worked out by the time the video goes up so I won't show any problems in the video.
Thanks for the cool mod!

**Comment by JimiIT92** [comment]
Wow, thank you so much! :D Of course this is not the intented behavior, you should still be able to put multiple non stackable items inside the Bundle, I guess. Consider that the functionality is just theorethical based on what we seen
