### ISSUE TITLE
Update the bundles behaviour to match the latest 1.17 snapshots

### ISSUE THREAD

**Issue by Seangles** [JimiIT92/BundlesMod#5]
Make bundles to match these criterias:
1) You may use the new bundle textures;
2) Redo the stacking mechanics:
2.1) Make so a bundle can store full stack of items of one type (not just half, because it doesn't make sense how you did that);
2.2) A bundle can store only 16 items of 16-stackable things (ie eggs, ender pearls), 64 items of 64-stackable things, only one non-stackable item;
2.3) A bundle can store for example 48 cobblestone blocks and only 4 ender pearls until it fills;
3) Make the tooltip preview to match the new one (they made it so it shows you a table of items inside);
4) Make the bundle freeing up mechanics like Mojang did, ie you can get the latest item you put in it, also you now can just throw out the insides of the bundle if you put it in your hand and shift-click it.
5) If you throw out the insides of a bundle (for example when you don't have enough space in inventory or shift-click it) the items are thrown is one direction (just copy the new 1.17 snapshot's mechanic);
6) Bundles are crafted from rabbit's leather.
I think that's all. 

Additional context:
The main concept of a bundle is to free up slots in inventory of junk like seeds or rotten flesh but not to add any extra space, it's not a shulker box. A bundle should be able to store a full stack of one type of item, not just the half of it, because it kinda doesn't make any sense. For example why can it store 32 cobblestone and 32 dirt, but can't store 60 dirt and 4 cobblestone? 
Otherwise it's a great mod, for some reason there is no any other mods that copy the bundles from upcoming 1.17 except this one.

Also in 1.17 snapshots you are able to put bundles into bundles, and it's very convenient, but is too complicated to implement. If you can make them to stack each other it would be great, I won't describe how they work but you can just check the 1.17 yourself :P

**Comment by JimiIT92** [comment]
Yes, Bundle behaviour will match the final result of Minecraft 1.17 (or at least it will be very close, depending on how much can be done with Forge 1.16.x). I'm just waiting to see if there are any changes, like they did in recent snapshots. When they will stop touching it for some time I will consider them finish and so update the mod :)

**Comment by JimiIT92** [comment]
Added in version 1.4
https://www.curseforge.com/minecraft/mc-mods/bundles-mod/files/3903683
